# Generated by Django 5.1.1 on 2024-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
