# Generated by Django 5.1.1 on 2024-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_scrap_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
