# Generated by Django 5.1.1 on 2024-11-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomePage', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Boletin_Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.user')),
                ('boletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IA.petition')),
            ],
            options={
                'unique_together': {('user', 'boletin')},
            },
        ),
    ]
